### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Boris-73-TA**
- Added OrthogPolyKANs contribution

### CODE REVIEW

**Comment by Boris-73-TA** [comment]
Attempting to add OrthogPolyKANs contribution

**Comment by kolmogorov-quyet** [comment]
Please push link github , not found when search google

**Comment by Boris-73-TA** [comment]
Hi kolmogorov-quyet, thanks for your comment. Could you please clarify what you mean by "push link github"? Are you looking for the repository link or specific details within the repository? I'm happy to provide more information to help evaluate this pull request effectively.

You can view the repository here: [OrthogPolyKANs](https://github.com/Boris-73-TA/OrthogPolyKANs)

**Comment by kolmogorov-quyet** [comment]
Thank you, that's correct, because I searched gg OrthogPolyKANs github but couldn't find it.

**Comment by mintisan** [comment]
thanks, merged

**Pull request merged**
